// Python Quiz Questions (90問)
const QUESTIONS=[
  {cat:'Python基礎',diff:'easy',type:'choice',q:'以下のコードの出力は何ですか？',code:'x = 10\ny = 3\nprint(x % y)',choices:['0','1','3','30'],ans:1,expl:'10 % 3 は余り → 1'},
  {cat:'Python基礎',diff:'easy',type:'choice',q:'リストの最後の要素を取り出す正しい方法は？',code:'my_list = [1, 2, 3, 4, 5]',choices:['my_list[-1]','my_list[last]','my_list.last()','my_list[len-1]'],ans:0,expl:'[-1] で末尾を参照'},
  {cat:'データ型',diff:'easy',type:'choice',q:'次のコードの出力結果は？',code:'print(type(3.14))',choices:["<class 'int'>","<class 'str'>","<class 'float'>","<class 'double'>"],ans:2,expl:'3.14 は float'},
  {cat:'文字列',diff:'easy',type:'choice',q:'文字列を繰り返すと？',code:'print("Ha" * 3)',choices:['Ha3','HaHaHa','Ha Ha Ha','Error'],ans:1,expl:'"Ha" * 3 = "HaHaHa"'},
  {cat:'Python基礎',diff:'easy',type:'choice',q:'Pythonでコメントを書く正しい記号は？',choices:['//','#','/*','--'],ans:1,expl:'# がコメント'},
  {cat:'リスト',diff:'easy',type:'choice',q:'このコードで nums の長さは？',code:'nums = [1, 2, 3]\nnums.append(4)\nnums.append(5)',choices:['3','4','5','6'],ans:2,expl:'3 + append×2 = 5'},
  {cat:'条件分岐',diff:'easy',type:'choice',q:'次のコードで出力されるのは？',code:'x = 7\nif x > 5:\n    print("大")\nelse:\n    print("小")',choices:['大','小','7','エラー'],ans:0,expl:'7 > 5 → "大"'},
  {cat:'Python基礎',diff:'easy',type:'fill',q:'リストの要素数を返す組み込み関数は？（関数名のみ）',code:'my_list = [1, 2, 3]\nprint(_____(my_list))  # 3',ans:'len',expl:'len() で長さを返す',hint:'l から始まる3文字'},
  {cat:'ループ',diff:'easy',type:'fill',q:'1から10までの合計は？（数字のみ）',code:'total = sum(range(1, 11))\nprint(total)',ans:'55',expl:'1+2+…+10 = 55'},
  {cat:'内包表記',diff:'normal',type:'choice',q:'リスト内包表記の出力は？',code:'result = [x**2 for x in range(5) if x % 2 == 0]\nprint(result)',choices:['[0, 4, 16]','[0, 2, 4]','[1, 4, 9]','[0, 1, 4]'],ans:0,expl:'偶数(0,2,4)の2乗 → [0, 4, 16]'},
  {cat:'辞書',diff:'normal',type:'choice',q:'次のコードの出力は？',code:"d = {'a': 1, 'b': 2, 'c': 3}\nprint(sum(d.values()))",choices:['abc','3','6','Error'],ans:2,expl:'1+2+3 = 6'},
  {cat:'再帰',diff:'normal',type:'choice',q:'この関数の mystery(6) の戻り値は？',code:'def mystery(n):\n    if n <= 1: return n\n    return mystery(n-1) + mystery(n-2)',choices:['8','13','21','5'],ans:0,expl:'フィボナッチ。mystery(6)=8'},
  {cat:'スライス',diff:'normal',type:'choice',q:'以下のスライスの結果は？',code:'s = "Python"\nprint(s[1:4])',choices:['Pyt','yth','ytho','ython'],ans:1,expl:'s[1:4] → "yth"'},
  {cat:'例外処理',diff:'normal',type:'choice',q:'次のコードの出力は？',code:'try:\n    x = 10 / 0\nexcept ZeroDivisionError:\n    print("ゼロ除算")\nfinally:\n    print("終了")',choices:['ゼロ除算のみ','終了のみ','ゼロ除算\n終了','停止'],ans:2,expl:'except + finally'},
  {cat:'lambda',diff:'normal',type:'choice',q:'ラムダ式の実行結果は？',code:'f = lambda x, y: x * y + y\nprint(f(3, 4))',choices:['12','16','13','19'],ans:1,expl:'3*4+4=16'},
  {cat:'文字列操作',diff:'normal',type:'choice',q:'以下のコードの出力は？',code:'words = ["apple","banana","cherry"]\nprint(", ".join(sorted(words, key=len)))',choices:['apple, banana, cherry','apple, cherry, banana','cherry, banana, apple','banana, apple, cherry'],ans:1,expl:'長さソート'},
  {cat:'文字列',diff:'normal',type:'fill',q:'文字列を大文字に変換するメソッドは？（メソッド名のみ）',code:'s = "hello"\nprint(s.___())  # HELLO',ans:'upper',expl:'.upper()で大文字に',hint:'"大文字"を意味する英単語'},
  {cat:'辞書',diff:'normal',type:'fill',q:'KeyError を避けてデフォルト値を返すメソッドは？',code:"d = {'x': 10}\nval = d.___('y', 0)  # → 0",ans:'get',expl:'.get(key, default)',hint:'3文字の英単語'},
  {cat:'デコレータ',diff:'hard',type:'choice',q:'デコレータの出力は？',code:'def double(func):\n    def wrapper(x):\n        return func(x) * 2\n    return wrapper\n\n@double\ndef add_one(x):\n    return x + 1\n\nprint(add_one(5))',choices:['6','11','12','10'],ans:2,expl:'add_one(5)=6 → ×2=12'},
  {cat:'ジェネレータ',diff:'hard',type:'choice',q:'フィボナッチの最初の5要素は？',code:'def fib():\n    a, b = 0, 1\n    while True:\n        yield a\n        a, b = b, a + b',choices:['[1,1,2,3,5]','[0,1,1,2,3]','[0,1,2,3,5]','[1,2,3,5,8]'],ans:1,expl:'0,1,1,2,3'},
  {cat:'クロージャ',diff:'hard',type:'choice',q:'クロージャの出力は？',code:'def make_counter():\n    count = 0\n    def inc():\n        nonlocal count\n        count += 1\n        return count\n    return inc\n\nc = make_counter()\nprint(c(), c(), c())',choices:['0 1 2','1 1 1','1 2 3','0 0 0'],ans:2,expl:'nonlocal → 1,2,3'},
  {cat:'クラス継承',diff:'hard',type:'choice',q:'このコードの出力は？',code:'class Animal:\n    sound = "..."\n    def speak(self):\n        return f"I say {self.sound}"\n\nclass Dog(Animal):\n    sound = "Woof"\n\nprint(Dog().speak())',choices:['I say ...','I say Woof','Woof','Error'],ans:1,expl:'Dog.sound="Woof"'},
  {cat:'辞書内包表記',diff:'hard',type:'choice',q:'辞書内包表記の結果は？',code:"data = [('a',1),('b',2),('c',3)]\nresult = {k:v**2 for k,v in data if v>1}\nprint(result)",choices:["{'a':1,'b':4,'c':9}","{'b':4,'c':9}","{'b':2,'c':3}","{'a':1}"],ans:1,expl:"v>1 → {'b':4,'c':9}"},
  {cat:'型',diff:'hard',type:'choice',q:'引数なしで呼んだ結果は？',code:"from typing import Optional\ndef greet(name: Optional[str] = None) -> str:\n    if name is None:\n        return 'Hello, World!'\n    return f'Hello, {name}!'\nprint(greet())",choices:['Hello, None!','TypeError','Hello, World!','Hello, !'],ans:2,expl:'name=None → Hello, World!'},
  {cat:'*args/**kwargs',diff:'hard',type:'fill',q:'可変長キーワード引数の変数名は？（慣例的に使う名前）',code:'def func(**_____):\n    print(_____)',ans:'kwargs',expl:'**kwargsが慣例',hint:'keyword arguments の略'},

  // ── 追加 EASY (15問) ──
  {cat:'Python基礎',diff:'easy',type:'choice',q:'変数 x に 5 を代入する正しい書き方は？',choices:['x == 5','x = 5','x := 5','let x = 5'],ans:1,expl:'= は代入演算子'},
  {cat:'演算',diff:'easy',type:'choice',q:'次のコードの出力は？',code:'print(2 ** 3)',choices:['6','8','5','23'],ans:1,expl:'2 ** 3 は 2の3乗 = 8'},
  {cat:'文字列',diff:'easy',type:'choice',q:'文字列の長さを求めるには？',code:'s = "Python"',choices:['s.length','s.size()','len(s)','s.count()'],ans:2,expl:'len() で文字列の長さ'},
  {cat:'リスト',diff:'easy',type:'choice',q:'リストの要素を逆順にするメソッドは？',choices:['.sort()','.reverse()','.flip()','.invert()'],ans:1,expl:'.reverse() で逆順に'},
  {cat:'bool',diff:'easy',type:'choice',q:'次の式の結果は？',code:'print(True and False)',choices:['True','False','None','Error'],ans:1,expl:'True and False = False'},
  {cat:'型変換',diff:'easy',type:'choice',q:'文字列 "42" を整数に変換するには？',choices:['int("42")','str(42)','float("42")','number("42")'],ans:0,expl:'int() で整数に変換'},
  {cat:'リスト',diff:'easy',type:'choice',q:'空のリストを作る2つの方法のうち正しいのは？',choices:['list() と []','array() と {}','new List()','List.create()'],ans:0,expl:'list() または [] で空リスト'},
  {cat:'ループ',diff:'easy',type:'choice',q:'次のコードの出力は？',code:'for i in range(3):\n    print(i, end=" ")',choices:['1 2 3','0 1 2','0 1 2 3','1 2'],ans:1,expl:'range(3) → 0, 1, 2'},
  {cat:'文字列',diff:'easy',type:'choice',q:'文字列の結合はどれ？',code:'a = "Hello"\nb = "World"',choices:['a + " " + b','a & b','a . b','concat(a, b)'],ans:0,expl:'+ で文字列結合'},
  {cat:'Python基礎',diff:'easy',type:'choice',q:'None の型は？',code:'print(type(None))',choices:["<class 'bool'>","<class 'NoneType'>","<class 'null'>","<class 'void'>"],ans:1,expl:'None は NoneType'},
  {cat:'比較',diff:'easy',type:'choice',q:'次の式の結果は？',code:'print(5 == 5.0)',choices:['True','False','Error','None'],ans:0,expl:'5 == 5.0 は True（値が同じ）'},
  {cat:'リスト',diff:'easy',type:'fill',q:'リストに要素を追加するメソッドは？（メソッド名のみ）',code:'lst = [1, 2]\nlst._____(3)  # [1, 2, 3]',ans:'append',expl:'.append() で末尾に追加',hint:'a から始まる6文字'},
  {cat:'Python基礎',diff:'easy',type:'fill',q:'画面に文字を表示する関数は？（関数名のみ）',code:'_____("Hello!")',ans:'print',expl:'print() で出力',hint:'p から始まる5文字'},
  {cat:'型変換',diff:'easy',type:'fill',q:'整数を文字列に変換する関数は？（関数名のみ）',code:'x = 42\ns = _____(x)  # "42"',ans:'str',expl:'str() で文字列に',hint:'3文字の関数'},
  {cat:'演算',diff:'easy',type:'fill',q:'15 を 4 で割った商（整数除算）は？（数字のみ）',code:'print(15 // 4)',ans:'3',expl:'// は整数除算（切り捨て）'},

  // ── 追加 EASY その2 (15問) ──
  {cat:'リスト',diff:'easy',type:'choice',q:'次のコードの出力は？',code:'print([1,2,3] + [4,5])',choices:['[1,2,3,4,5]','[5,7]','Error','9'],ans:0,expl:'+ でリストを結合'},
  {cat:'文字列',diff:'easy',type:'choice',q:'次のコードの出力は？',code:'print("hello"[0])',choices:['h','e','hello','1'],ans:0,expl:'[0] は最初の文字'},
  {cat:'比較',diff:'easy',type:'choice',q:'次の式の結果は？',code:'print(10 != 10)',choices:['True','False','Error','10'],ans:1,expl:'10 != 10 は False'},
  {cat:'Python基礎',diff:'easy',type:'choice',q:'Pythonで改行なしで出力するには？',choices:['print(x, end="")','print(x, \\n=False)','echo(x)','write(x)'],ans:0,expl:'end="" で改行を抑制'},
  {cat:'文字列',diff:'easy',type:'choice',q:'次のコードの出力は？',code:'print("abc".upper())',choices:['abc','ABC','Abc','Error'],ans:1,expl:'.upper() で全て大文字'},
  {cat:'リスト',diff:'easy',type:'choice',q:'リストの先頭の要素を削除するには？',code:'a = [1, 2, 3]',choices:['a.pop(0)','a.remove_first()','a.delete(0)','del a.first'],ans:0,expl:'.pop(0) で先頭を削除して返す'},
  {cat:'bool',diff:'easy',type:'choice',q:'次の式の結果は？',code:'print(not True)',choices:['True','False','None','Error'],ans:1,expl:'not True は False'},
  {cat:'Python基礎',diff:'easy',type:'choice',q:'空文字列の真偽値は？',code:'print(bool(""))',choices:['True','False','""','Error'],ans:1,expl:'空文字列は False'},
  {cat:'リスト',diff:'easy',type:'choice',q:'次のコードの出力は？',code:'print(max([3, 1, 4, 1, 5]))',choices:['1','3','5','15'],ans:2,expl:'max() で最大値 = 5'},
  {cat:'文字列',diff:'easy',type:'choice',q:'次のコードの出力は？',code:'print("hello world".replace("world", "Python"))',choices:['hello world','hello Python','Python world','Error'],ans:1,expl:'.replace() で置換'},
  {cat:'演算',diff:'easy',type:'fill',q:'3 + 4 * 2 の結果は？（数字のみ）',code:'print(3 + 4 * 2)',ans:'11',expl:'掛け算が先: 4*2=8, 3+8=11'},
  {cat:'リスト',diff:'easy',type:'fill',q:'[1,2,3] の合計は？（数字のみ）',code:'print(sum([1, 2, 3]))',ans:'6',expl:'sum() で合計 = 6'},
  {cat:'文字列',diff:'easy',type:'fill',q:'文字列を小文字に変換するメソッドは？（メソッド名のみ）',code:'s = "HELLO"\nprint(s.___())  # hello',ans:'lower',expl:'.lower() で小文字に',hint:'5文字のメソッド'},
  {cat:'Python基礎',diff:'easy',type:'fill',q:'整数の最大値を返す関数は？（関数名のみ）',code:'print(_____(3, 7, 1))  # 7',ans:'max',expl:'max() で最大値',hint:'3文字の関数'},
  {cat:'Python基礎',diff:'easy',type:'fill',q:'入力を受け取る関数は？（関数名のみ）',code:'name = _____("名前: ")',ans:'input',expl:'input() でユーザー入力',hint:'5文字の関数'},

  // ── 追加 NORMAL (20問) ──
  {cat:'集合',diff:'normal',type:'choice',q:'次のコードの出力は？',code:'s = {1, 2, 3, 2, 1}\nprint(len(s))',choices:['5','3','2','Error'],ans:1,expl:'集合は重複なし → {1,2,3}'},
  {cat:'文字列',diff:'normal',type:'choice',q:'次のコードの出力は？',code:'s = "hello world"\nprint(s.title())',choices:['HELLO WORLD','hello world','Hello World','Hello world'],ans:2,expl:'.title() は各単語の先頭を大文字に'},
  {cat:'リスト',diff:'normal',type:'choice',q:'次のコードの出力は？',code:'a = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)',choices:['[1, 2, 3]','[1, 2, 3, 4]','Error','[4]'],ans:1,expl:'b = a は参照コピー。同じリストを指す'},
  {cat:'辞書',diff:'normal',type:'choice',q:'次のコードの出力は？',code:"d = {'a':1,'b':2,'c':3}\nprint(list(d.keys()))",choices:["['a','b','c']","[1,2,3]","[('a',1),('b',2)]","Error"],ans:0,expl:'.keys() でキーの一覧'},
  {cat:'文字列',diff:'normal',type:'choice',q:'次のコードの出力は？',code:'print("Python"[::2])',choices:['Pto','yhn','Pyth','Py'],ans:0,expl:'[::2] はステップ2 → P,t,o'},
  {cat:'関数',diff:'normal',type:'choice',q:'次のコードの出力は？',code:'def f(x, y=10):\n    return x + y\nprint(f(5))',choices:['5','10','15','Error'],ans:2,expl:'y のデフォルト値10 → 5+10=15'},
  {cat:'タプル',diff:'normal',type:'choice',q:'タプルについて正しいのは？',choices:['変更可能(mutable)','変更不可(immutable)','辞書と同じ','キーがある'],ans:1,expl:'タプルは immutable'},
  {cat:'文字列',diff:'normal',type:'choice',q:'次のコードの出力は？',code:'print("apple,banana,cherry".split(","))',choices:["['apple','banana','cherry']","'apple banana cherry'","('apple','banana','cherry')","Error"],ans:0,expl:'.split() で分割してリストに'},
  {cat:'ループ',diff:'normal',type:'choice',q:'次のコードの出力は？',code:'x = 0\nwhile x < 5:\n    x += 2\nprint(x)',choices:['4','5','6','10'],ans:2,expl:'0→2→4→6（6で条件False、ループ終了）'},
  {cat:'リスト',diff:'normal',type:'choice',q:'次のコードの出力は？',code:'a = [3, 1, 4, 1, 5]\nprint(sorted(a))',choices:['[5, 4, 3, 1, 1]','[1, 1, 3, 4, 5]','[3, 1, 4, 1, 5]','Error'],ans:1,expl:'sorted() は昇順ソート'},
  {cat:'集合',diff:'normal',type:'choice',q:'2つの集合の共通要素は？',code:'a = {1, 2, 3}\nb = {2, 3, 4}\nprint(a & b)',choices:['{1, 4}','{2, 3}','{1, 2, 3, 4}','Error'],ans:1,expl:'& は積集合（共通要素）'},
  {cat:'enumerate',diff:'normal',type:'choice',q:'次のコードの出力は？',code:'for i, v in enumerate(["a","b","c"]):\n    if i == 1:\n        print(v)',choices:['a','b','c','1'],ans:1,expl:'enumerate: i=1のときv="b"'},
  {cat:'三項演算子',diff:'normal',type:'choice',q:'次のコードの出力は？',code:'x = 7\nresult = "偶数" if x % 2 == 0 else "奇数"\nprint(result)',choices:['偶数','奇数','7','Error'],ans:1,expl:'7 % 2 != 0 → "奇数"'},
  {cat:'zip',diff:'normal',type:'choice',q:'次のコードの出力は？',code:'a = [1, 2, 3]\nb = ["a", "b", "c"]\nprint(list(zip(a, b)))',choices:['[(1,"a"),(2,"b"),(3,"c")]','[1,"a",2,"b",3,"c"]','{"1":"a","2":"b"}','Error'],ans:0,expl:'zip で対応する要素をタプルに'},
  {cat:'map',diff:'normal',type:'choice',q:'次のコードの出力は？',code:'nums = [1, 2, 3, 4]\nresult = list(map(lambda x: x * 2, nums))\nprint(result)',choices:['[1, 2, 3, 4]','[2, 4, 6, 8]','[1, 4, 9, 16]','Error'],ans:1,expl:'map で各要素を2倍'},
  {cat:'文字列',diff:'normal',type:'fill',q:'文字列の前後の空白を除去するメソッドは？',code:'s = "  hello  "\nprint(s.___())  # "hello"',ans:'strip',expl:'.strip() で前後の空白を除去',hint:'5文字のメソッド'},
  {cat:'リスト',diff:'normal',type:'fill',q:'リストの要素を昇順に並べ替えるメソッドは？',code:'a = [3, 1, 2]\na._____()\nprint(a)  # [1, 2, 3]',ans:'sort',expl:'.sort() で昇順ソート',hint:'4文字のメソッド'},
  {cat:'数学',diff:'normal',type:'fill',q:'絶対値を返す組み込み関数は？（関数名のみ）',code:'print(_____(-7))  # 7',ans:'abs',expl:'abs() で絶対値',hint:'3文字の関数'},
  {cat:'演算',diff:'normal',type:'fill',q:'2の10乗は？（数字のみ）',code:'print(2 ** 10)',ans:'1024',expl:'2^10 = 1024'},
  {cat:'文字列',diff:'normal',type:'fill',q:'文字列中の特定文字の出現回数を数えるメソッドは？',code:'s = "banana"\nprint(s._____("a"))  # 3',ans:'count',expl:'.count() で出現回数',hint:'5文字のメソッド'},

  // ── 追加 HARD (15問) ──
  {cat:'内包表記',diff:'hard',type:'choice',q:'ネストしたリスト内包表記の結果は？',code:'matrix = [[1,2],[3,4],[5,6]]\nflat = [x for row in matrix for x in row]\nprint(flat)',choices:['[[1,2],[3,4],[5,6]]','[1,2,3,4,5,6]','[1,3,5,2,4,6]','Error'],ans:1,expl:'ネスト内包でフラット化'},
  {cat:'集合演算',diff:'hard',type:'choice',q:'次のコードの出力は？',code:'a = {1,2,3,4}\nb = {3,4,5,6}\nprint(a ^ b)',choices:['{3,4}','{1,2,5,6}','{1,2,3,4,5,6}','Error'],ans:1,expl:'^ は対称差（片方にのみ含まれる要素）'},
  {cat:'アンパック',diff:'hard',type:'choice',q:'次のコードの出力は？',code:'a, *b, c = [1, 2, 3, 4, 5]\nprint(b)',choices:['[2, 3, 4]','[1, 2, 3]','2','Error'],ans:0,expl:'*b が中間の要素をキャプチャ'},
  {cat:'walrus',diff:'hard',type:'choice',q:'次のコードの出力は？',code:'data = [1, 2, 3, 4, 5]\nif (n := len(data)) > 3:\n    print(n)',choices:['3','5','True','Error'],ans:1,expl:':= (walrus演算子) で代入と評価を同時に'},
  {cat:'関数',diff:'hard',type:'choice',q:'次のコードの出力は？',code:'def f(a, b, /, c, *, d):\n    return a + b + c + d\nprint(f(1, 2, c=3, d=4))',choices:['10','Error','4','None'],ans:0,expl:'/ の前は位置のみ、* の後はキーワードのみ'},
  {cat:'イテレータ',diff:'hard',type:'choice',q:'次のコードの出力は？',code:'it = iter([10, 20, 30])\nnext(it)\nprint(next(it))',choices:['10','20','30','Error'],ans:1,expl:'1回目のnextで10を消費、2回目で20'},
  {cat:'文字列',diff:'hard',type:'choice',q:'次のコードの出力は？',code:'s = "abcdef"\nprint(s[-3::-2])',choices:["'db'","'df'","'dba'","'bdf'"],ans:0,expl:'s[-3::-2] → index3(d)から逆方向ステップ2 → d,b'},
  {cat:'クラス',diff:'hard',type:'choice',q:'次のコードの出力は？',code:'class A:\n    x = []\n    def add(self, v):\n        self.x.append(v)\n\na = A()\nb = A()\na.add(1)\nprint(b.x)',choices:['[]','[1]','Error','None'],ans:1,expl:'クラス変数のリストは全インスタンスで共有'},
  {cat:'ビット演算',diff:'hard',type:'choice',q:'次の式の結果は？',code:'print(0b1010 & 0b1100)',choices:['8','10','12','6'],ans:0,expl:'1010 & 1100 = 1000 = 8'},
  {cat:'any/all',diff:'hard',type:'choice',q:'次のコードの出力は？',code:'print(all([True, 1, "hello", [0]]))',choices:['True','False','Error','None'],ans:0,expl:'全て truthy → all() は True'},
  {cat:'collections',diff:'hard',type:'choice',q:'Counter の most_common(1) の結果は？',code:'from collections import Counter\nc = Counter("abracadabra")\nprint(c.most_common(1))',choices:["[('a', 5)]","[('b', 2)]","{'a': 5}","[5]"],ans:0,expl:'a が5回で最頻出'},
  {cat:'内包表記',diff:'hard',type:'fill',q:'このリスト内包表記の結果の長さは？（数字のみ）',code:'result = [i for i in range(100) if i % 3 == 0 and i % 5 == 0]\nprint(len(result))',ans:'7',expl:'FizzBuzz: 0,15,30,45,60,75,90 → 7個'},
  {cat:'再帰',diff:'hard',type:'fill',q:'この関数の出力は？（数字のみ）',code:'def f(n):\n    if n == 0: return 1\n    return n * f(n-1)\nprint(f(5))',ans:'120',expl:'5! = 120（階乗）'},
  {cat:'ビット演算',diff:'hard',type:'fill',q:'次の式の結果は？（数字のみ）',code:'print(1 << 4)',ans:'16',expl:'1を左に4ビットシフト = 16'},
  {cat:'文字列',diff:'hard',type:'fill',q:'次のコードの出力は？（数字のみ）',code:'print(ord("A"))',ans:'65',expl:'ord("A") = 65（ASCII値）'},

  // ── 追加 EASY その3 (15問) ──
  {cat:'リスト',diff:'easy',type:'choice',q:'次のコードの出力は？',code:'a = [10, 20, 30]\nprint(a[1])',choices:['10','20','30','Error'],ans:1,expl:'インデックス1は2番目の要素 = 20'},
  {cat:'演算',diff:'easy',type:'choice',q:'次のコードの出力は？',code:'print(10 // 3)',choices:['3.33','3','1','10'],ans:1,expl:'// は整数除算（切り捨て）= 3'},
  {cat:'文字列',diff:'easy',type:'choice',q:'次のコードの出力は？',code:'s = "Hello"\nprint(s * 2)',choices:['Hello2','HelloHello','10','Error'],ans:1,expl:'文字列 * 2 は繰り返し'},
  {cat:'リスト',diff:'easy',type:'choice',q:'リストの要素を全部消すメソッドは？',choices:['.clear()','.delete()','.removeAll()','.empty()'],ans:0,expl:'.clear() でリストを空にする'},
  {cat:'bool',diff:'easy',type:'choice',q:'次の式の結果は？',code:'print(True or False)',choices:['True','False','None','Error'],ans:0,expl:'True or False = True'},
  {cat:'Python基礎',diff:'easy',type:'choice',q:'次のコードの出力は？',code:'x = 5\nx += 3\nprint(x)',choices:['5','3','8','53'],ans:2,expl:'x += 3 は x = x + 3 = 8'},
  {cat:'リスト',diff:'easy',type:'choice',q:'次のコードの出力は？',code:'a = [1, 2, 3]\na.insert(1, 10)\nprint(a)',choices:['[1, 10, 2, 3]','[10, 1, 2, 3]','[1, 2, 10, 3]','Error'],ans:0,expl:'insert(1, 10) でインデックス1に10を挿入'},
  {cat:'文字列',diff:'easy',type:'choice',q:'次のコードの出力は？',code:'print("Python".startswith("Py"))',choices:['True','False','Py','Error'],ans:0,expl:'"Python"は"Py"で始まる → True'},
  {cat:'比較',diff:'easy',type:'choice',q:'次の式の結果は？',code:'print(3 > 2 > 1)',choices:['True','False','Error','None'],ans:0,expl:'Pythonでは連鎖比較が可能 → True'},
  {cat:'リスト',diff:'easy',type:'choice',q:'次のコードの出力は？',code:'print(min([5, 3, 8, 1, 4]))',choices:['1','3','5','8'],ans:0,expl:'min() で最小値 = 1'},
  {cat:'Python基礎',diff:'easy',type:'fill',q:'次のコードの出力は？（数字のみ）',code:'print(abs(-8))',ans:'8',expl:'abs() で絶対値 = 8'},
  {cat:'リスト',diff:'easy',type:'fill',q:'次のコードの出力は？（数字のみ）',code:'print(len("Hello"))',ans:'5',expl:'文字列の長さ = 5'},
  {cat:'演算',diff:'easy',type:'fill',q:'次のコードの出力は？（数字のみ）',code:'print(2 + 3 * 4)',ans:'14',expl:'掛け算が先: 3*4=12, 2+12=14'},
  {cat:'文字列',diff:'easy',type:'fill',q:'次のコードの出力は？',code:'print("abc"[2])',ans:'c',expl:'インデックス2は3番目の文字 = c'},
  {cat:'bool',diff:'easy',type:'fill',q:'次のコードの出力は？',code:'print(10 > 5)',ans:'True',expl:'10 > 5 は True'},
];

// ═══════════════════════════════════
//  CIPHER STAGES (from escape game)
